#define HOLOMAP_AREACOLOR_COMMAND "#00006dcc"
#define HOLOMAP_AREACOLOR_SECURITY "#bdbdbdcc"
#define HOLOMAP_AREACOLOR_MEDICAL "#638fc2cc"
#define HOLOMAP_AREACOLOR_GENERIC_ROOM "#358030cc"
#define HOLOMAP_AREACOLOR_ENGINEERING "#F1C231cc"
#define HOLOMAP_AREACOLOR_CARGO "#9e642299"
#define HOLOMAP_AREACOLOR_HALLWAYS "#8f8f8fcc"
#define HOLOMAP_AREACOLOR_SCIENCE "#191ca5cc"
#define HOLOMAP_AREACOLOR_MAINTENANCE "#363636cc"

#define HOLOMAP_COLOR_EXTERNAL_AIRLOCK "#ff8080cc"
#define HOLOMAP_COLOR_WALL "#ffffffcc"

/// Dimensions of the holomap. This is NOT MEANT TO BE CHANGED, its just for readability.
#define HOLOMAP_SIZE 480
